### ISSUE TITLE
Not able to run Algorand Studio on Apple M1 Mac Pro

### ISSUE THREAD

**Issue by akshaykant** [ObsidianLabs/AlgorandStudio#14]
I am getting this error while running the Algorand Studio on M1-chip Mac laptop. Could someone please assist with this.

<img width="263" alt="Screenshot 2021-01-19 at 15 13 50" src="https://user-images.githubusercontent.com/7160559/105053539-f648d900-5a68-11eb-95c9-5d4be7b5b6b0.png">

**Comment by KBryan** [comment]
That is common if you are downloading a Mac app that isn't from the app store. From Search -> System Preferences ->  Security and Privacy -> Allow apps downloaded from and you should see the app you are trying to install.

**Comment by leonlianght** [comment]
BTW we are working on the native M1 support
